apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
  namespace: ejemplito
  labels:
    app: micros
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micros
  template:
    metadata:
      labels:
        app: micros
    spec:
      containers:
      - name: client
        image: contenedoreskubev2.azurecr.io/microclient:latest 
        ports:
        - containerPort: 8000
        env: 
          - name: SIMPSONS_API
            value: "https://thesimpsonsapi.com/api/characters/"
          - name: AUDIT_API
            value: "http://api-backend-service:8080"
          - name: AUDIT_API.SAVE_ENDPOINT
            value: "/api/java/v1/simpson"
      - name: service
        image: contenedoreskubev2.azurecr.io/microservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: url
          value: jdbc:mysql://serverflexmysqlv1.mysql.database.azure.com:3306/pokeaudit?useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        - name: user
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: user
        - name: pass
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: pass