apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: ejemplito
spec:
  ingressClassName: nginx
  rules:
  
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-service
            port:
              number: 80

      - path: /api/python
        pathType: Prefix
        backend:
          service:
            name: api-backend-service
            port:
              number: 8000

      - path: /api/java
        pathType: Prefix
        backend:
          service:
            name: api-backend-service
            port:
              number: 8080